name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Set short SHA
      id: vars
      run: echo "SHORT_SHA=${GITHUB_SHA::5}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        docker build \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-k8s-insights:latest \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/simple-k8s-insights:${{ env.SHORT_SHA }} \
          .

    - name: Push Docker Images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-k8s-insights:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple-k8s-insights:${{ env.SHORT_SHA }}
